package com.recordmanagement.app;
import java.awt.Color;
/**
 *
 * @author Glyde Llait
 */
public class FrmAccountt extends javax.swing.JFrame {
    public FrmAccountt() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIcon();
        CBDivision.setBackground(Color.white);
        CBDivision.getModel().setSelectedItem("Select Division");
    }
    private void setIcon() {
        LoginPage setIconImage;
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    } 
    final javax.swing.ImageIcon failed = new javax.swing.ImageIcon(getClass().getResource("Sad.png"));
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblRetype = new javax.swing.JLabel();
        PanelTitle = new javax.swing.JPanel();
        lblTitile = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtName = new javax.swing.JTextField();
        btnDone = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtRetype = new javax.swing.JPasswordField();
        lblIMAGE = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        CBDivision = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account - Diaz Dental Clinic System");
        setName("FrmAccount"); // NOI18N
        setUndecorated(true);

        PanelMain.setBackground(new java.awt.Color(17, 24, 42));
        PanelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name :");

        lblUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username :");

        lblPass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Password :");

        lblRetype.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRetype.setForeground(new java.awt.Color(255, 255, 255));
        lblRetype.setText("Re-type Password :");

        PanelTitle.setBackground(new java.awt.Color(17, 24, 42));
        PanelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitile.setForeground(new java.awt.Color(255, 255, 255));
        lblTitile.setText("Add User Account");

        javax.swing.GroupLayout PanelTitleLayout = new javax.swing.GroupLayout(PanelTitle);
        PanelTitle.setLayout(PanelTitleLayout);
        PanelTitleLayout.setHorizontalGroup(
            PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitile)
                .addGap(204, 204, 204))
        );
        PanelTitleLayout.setVerticalGroup(
            PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });

        txtPassword.setNextFocusableComponent(txtRetype);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        btnDone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recordmanagement/assets/check.png"))); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recordmanagement/assets/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtRetype.setNextFocusableComponent(btnBrowse);
        txtRetype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRetypeKeyPressed(evt);
            }
        });

        lblIMAGE.setBackground(new java.awt.Color(17, 24, 42));
        lblIMAGE.setForeground(new java.awt.Color(255, 255, 255));
        lblIMAGE.setText("                       Optional");
        lblIMAGE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnBrowse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recordmanagement/assets/browse.png"))); // NOI18N
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recordmanagement/assets/Delete.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        CBDivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Admin","Doctor","Secretary"}));
        CBDivision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CBDivisionKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Division :");

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPass)
                    .addComponent(lblRetype)
                    .addComponent(lblUsername)
                    .addComponent(lblName)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtName)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRetype)
                    .addComponent(CBDivision, 0, 138, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addComponent(btnBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove))
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblIMAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addComponent(lblIMAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRemove)
                            .addComponent(btnBrowse)))
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRetype)
                            .addComponent(txtRetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDone)
                    .addComponent(btnCancel))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        String division = (String) CBDivision.getSelectedItem();
        String name = txtName.getText();
        String username = txtUsername.getText();
        String pass = txtPassword.getText();
        String retype = txtRetype.getText();
        byte[] image = this.imgdata;
        if(division.equals("Select Division")){CBDivision.setBackground(Color.green);javax.swing.JOptionPane.showMessageDialog(null, "Invalid  Division","Error!",2,failed);CBDivision.setBackground(Color.white);}
        else if(name.equals("")){txtName.setBackground(Color.green);javax.swing.JOptionPane.showMessageDialog(null, "Invalid  Name","Error!",2,failed);txtName.setBackground(Color.white);}
        else if(username.equals("")){txtUsername.setBackground(Color.green);javax.swing.JOptionPane.showMessageDialog(null, "Invalid  Username.","Error!",2,failed);txtUsername.setBackground(Color.white);}
        else if(pass.equals("")){txtPassword.setBackground(Color.green);javax.swing.JOptionPane.showMessageDialog(null, "Invalid Password.","Error!",2,failed);txtPassword.setBackground(Color.white);
        }else{
        if(pass.equals(retype)){SQLite.openDB();
        if(SQLite.create("login","'"+username+"'"+","+"'"+pass+"'"+","+"'"+name+"','"+division+"', ''")){
            SQLite.update("login", image, "image", username);
            javax.swing.JOptionPane.showMessageDialog(null, name+" has been added!");
            dispose();
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(null, "Input another username.","Error!",2,failed);
        }
        SQLite.closeDB();
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "You enter different password.","Failed!",2,failed);
        }}
    }//GEN-LAST:event_btnDoneActionPerformed
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    private void txtRetypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetypeKeyPressed
         if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
        String division = (String) CBDivision.getSelectedItem();
        String name = txtName.getText();
        String username = txtUsername.getText();
        String pass = txtPassword.getText();
        String retype = txtRetype.getText();
        byte[] image = this.imgdata;
        if(division.equals("Select Division")){CBDivision.setBackground(Color.green);javax.swing.JOptionPane.showMessageDialog(null, "Invalid  Division","Error!",2,failed);CBDivision.setBackground(Color.white);}
        else if(name.equals("")){txtName.setBackground(Color.green);javax.swing.JOptionPane.showMessageDialog(null, "Invalid  Name","Error!",2,failed);txtName.setBackground(Color.white);}
        else if(username.equals("")){txtUsername.setBackground(Color.green);javax.swing.JOptionPane.showMessageDialog(null, "Invalid  Username.","Error!",2,failed);txtUsername.setBackground(Color.white);}
        else if(pass.equals("")){txtPassword.setBackground(Color.green);javax.swing.JOptionPane.showMessageDialog(null, "Invalid Password.","Error!",2,failed);txtPassword.setBackground(Color.white);
        }else{
        if(pass.equals(retype)){SQLite.openDB();
        if(SQLite.create("login","'"+username+"'"+","+"'"+pass+"'"+","+"'"+name+"',"+"'"+division+"', ''")){
            SQLite.update("login", image, "image", username);
            javax.swing.JOptionPane.showMessageDialog(null, name+" has been added!");
            dispose();
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(null, "Input another username.","Error!",2,failed);
        }
        SQLite.closeDB();
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "You enter different password.","Failed!",2,failed);
        }}
        }
                if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ESCAPE){
        dispose();}
    }//GEN-LAST:event_txtRetypeKeyPressed
    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.showOpenDialog(null);
        
        java.io.File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        
        java.io.File fimage = new java.io.File(filename);
        try{
            java.io.FileInputStream fis = new java.io.FileInputStream(fimage);
            java.io.ByteArrayOutputStream bos = new java.io.ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            imgdata = bos.toByteArray(); 
            
            java.awt.Image image = stretchImage(filename,this.lblIMAGE);
            this.lblIMAGE.setIcon(new javax.swing.ImageIcon(image));
        }
        catch(Exception e){
            System.out.println("FileInputStream Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBrowseActionPerformed
    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ESCAPE){dispose();}
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ESCAPE){dispose();}
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ESCAPE){dispose();}
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        lblIMAGE.setIcon(null);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void CBDivisionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CBDivisionKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ESCAPE){dispose();}
    }//GEN-LAST:event_CBDivisionKeyPressed
    private byte[] imgdata;
    public java.awt.Image stretchImage(String path,javax.swing.JLabel label){
        java.awt.Toolkit toolkit = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Image image = toolkit.getImage(path);
        java.awt.Image scaledImage = image.getScaledInstance(label.getWidth(),label.getHeight(), java.awt.Image.SCALE_DEFAULT);
        return scaledImage;
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAccountt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAccountt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAccountt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAccountt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAccountt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBDivision;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelTitle;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIMAGE;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRetype;
    private javax.swing.JLabel lblTitile;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRetype;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
