package com.recordmanagement.app;
import static com.recordmanagement.app.SQLite.conn;
import static com.recordmanagement.app.SQLite.url;
/**
 *
 * @author Glyde Llait
 */
public class FrmPassword extends javax.swing.JFrame {
    public FrmPassword() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtNew.setEnabled(false);
        txtRetype.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        lblOldPass = new javax.swing.JLabel();
        lblNewPass = new javax.swing.JLabel();
        lblRetypePass = new javax.swing.JLabel();
        txtNew = new javax.swing.JTextField();
        txtOld = new javax.swing.JPasswordField();
        txtRetype = new javax.swing.JPasswordField();
        btnDone = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        SeperatorPass = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password - Diaz Dental Clinic System");
        setUndecorated(true);

        MainPanel.setBackground(new java.awt.Color(0, 102, 102));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        lblOldPass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblOldPass.setForeground(new java.awt.Color(255, 255, 255));
        lblOldPass.setText("Old Password         : ");

        lblNewPass.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNewPass.setForeground(new java.awt.Color(255, 255, 255));
        lblNewPass.setText("New Password      :  ");

        lblRetypePass.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lblRetypePass.setForeground(new java.awt.Color(255, 255, 255));
        lblRetypePass.setText("Re-type Password : ");

        txtOld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOldKeyReleased(evt);
            }
        });

        txtRetype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRetypeKeyPressed(evt);
            }
        });

        btnDone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recordmanagement/assets/check.png"))); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recordmanagement/assets/cancel.png"))); // NOI18N
        btnReset.setText("Cancel");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SeperatorPass)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNewPass)
                            .addComponent(lblOldPass)
                            .addComponent(lblRetypePass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNew)
                            .addComponent(txtOld)
                            .addComponent(txtRetype)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOldPass)
                    .addComponent(txtOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(SeperatorPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPass)
                    .addComponent(txtNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRetypePass)
                    .addComponent(txtRetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDone)
                    .addComponent(btnReset))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String username = com.recordmanagement.classes.User.username;
    private void txtOldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldKeyReleased
        String query = "Select * FROM login WHERE username=? and password=?";
        
        try{
            conn = java.sql.DriverManager.getConnection(url);
            java.sql.PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1,username);
            ps.setString(2, txtOld.getText());
            java.sql.ResultSet rs = ps.executeQuery();
            if(rs.next()){
                txtNew.setEnabled(true);
                txtRetype.setEnabled(true);
            }else{
                txtNew.setEnabled(false);
                txtRetype.setEnabled(false);     
            }
            conn.close();
        }
        
        catch(Exception e){
            System.out.println("Old Password Error:" + e.getMessage());
        }
    }//GEN-LAST:event_txtOldKeyReleased
    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        String newPass = txtNew.getText();
        String retype = txtRetype.getText();
        String set = "password='"+retype+"'";
        if(newPass.equals(retype)){
            SQLite.openDB();
            if(newPass.equals("")){
            javax.swing.JOptionPane.showMessageDialog(null, "Password is empty.","Error",2);
            }else{
            SQLite.updateNoID(set,username);
            SQLite.closeDB();
            javax.swing.JOptionPane.showMessageDialog(null, "Password changed successful","Completed!",0,success);
            dispose();
        }}else{
        javax.swing.JOptionPane.showMessageDialog(null, "You enter different password.","Error",2);
        }
    }//GEN-LAST:event_btnDoneActionPerformed
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        dispose();
    }//GEN-LAST:event_btnResetActionPerformed
    private void txtRetypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetypeKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
        String newPass = txtNew.getText();
        String retype = txtRetype.getText();
        String set = "password='"+retype+"'";
        if(newPass.equals(retype)){
            SQLite.openDB();
            if(newPass.equals("")){
            javax.swing.JOptionPane.showMessageDialog(null, "Password is empty.","Error",2);
            }else{
            SQLite.updateNoID(set,username);
            SQLite.closeDB();
            javax.swing.JOptionPane.showMessageDialog(null, "Password changed successful","Completed!",0,success);
            dispose();
        }}else{
        javax.swing.JOptionPane.showMessageDialog(null, "You enter different password.","Error",2);
        }
        }
    }//GEN-LAST:event_txtRetypeKeyPressed
    private void txtOldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ESCAPE){
        dispose();}
    }//GEN-LAST:event_txtOldKeyPressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPassword().setVisible(true);
            }
        });
    }
    final javax.swing.ImageIcon success = new javax.swing.ImageIcon(getClass().getResource("Success.png"));
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JSeparator SeperatorPass;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JLabel lblRetypePass;
    private javax.swing.JTextField txtNew;
    private javax.swing.JPasswordField txtOld;
    private javax.swing.JPasswordField txtRetype;
    // End of variables declaration//GEN-END:variables
}
