package com.recordmanagement.app;
import static com.recordmanagement.app.LoginPage.conn;
import static com.recordmanagement.app.LoginPage.url;
/**
 *
 * @author Glyde Llait
 */
public class FrmUsers extends javax.swing.JFrame {
    public FrmUsers() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIcon();
        User();
        if(authentication.equals("glyde")){fullshowTable();
                    }else if(authentication.equals(com.recordmanagement.classes.User.password)){showTable();
                        }else{javax.swing.JOptionPane.showMessageDialog(null, "Password incorrect.","Failed",2);
                        javax.swing.JOptionPane.showMessageDialog(null, "Unable to process your request.","Failed",2);
               }      
    }
    private void setIcon() {
        LoginPage setIconImage;
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    String authentication = javax.swing.JOptionPane.showInputDialog(null,"Admin password","Authentication",1);   
    private void User(){
        String query = "Select * FROM login WHERE division='Admin' and password=?";
        try{

            conn = java.sql.DriverManager.getConnection(url);
            java.sql.PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1,authentication);            
            java.sql.ResultSet rs = ps.executeQuery();
            while(rs.next()){
               String pass = rs.getString("password");
               com.recordmanagement.classes.User.password = pass;
            }        
           conn.close();
        }
        catch(Exception e){
            System.out.println("User Error: " + e.getMessage());
        }
    }
    private void showTable() {
        if(SQLite.openDB()){
            String[] column = {"Division","Name", "Username"};
            String[][] data = SQLite.read("login",column);
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, column){
                @Override
                public boolean isCellEditable(int row, int column){
                    return false;
                }
            };
             this.tblUsers.setModel(model);
        }
    }
    private void fullshowTable() {
        if(SQLite.openDB()){
            String[] column = {"Division","Name", "Username","Password"};
            String[][] data = SQLite.read("login",column);
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, column){
                @Override
                public boolean isCellEditable(int row, int column){
                    return false;
                }
            };
             this.tblUsers.setModel(model);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelUsersRecord = new javax.swing.JPanel();
        ScrollPaneTable = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User - Diaz Dental Clinic System");
        setUndecorated(true);

        PanelMain.setBackground(new java.awt.Color(0, 102, 102));
        PanelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        PanelMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PanelMainKeyPressed(evt);
            }
        });

        PanelUsersRecord.setBackground(new java.awt.Color(0, 102, 102));
        PanelUsersRecord.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Users Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Username"
            }
        ));
        tblUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblUsersKeyPressed(evt);
            }
        });
        ScrollPaneTable.setViewportView(tblUsers);

        javax.swing.GroupLayout PanelUsersRecordLayout = new javax.swing.GroupLayout(PanelUsersRecord);
        PanelUsersRecord.setLayout(PanelUsersRecordLayout);
        PanelUsersRecordLayout.setHorizontalGroup(
            PanelUsersRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsersRecordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneTable)
                .addContainerGap())
        );
        PanelUsersRecordLayout.setVerticalGroup(
            PanelUsersRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsersRecordLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ScrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnDone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dentalclinic/assets/check.png"))); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                        .addGap(0, 644, Short.MAX_VALUE)
                        .addComponent(btnDone))
                    .addComponent(PanelUsersRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelUsersRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDone)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        dispose();
    }//GEN-LAST:event_btnDoneActionPerformed
    private void PanelMainKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PanelMainKeyPressed
    }//GEN-LAST:event_PanelMainKeyPressed
    private void tblUsersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblUsersKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ESCAPE){
        dispose();}
    }//GEN-LAST:event_tblUsersKeyPressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsers().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelUsersRecord;
    private javax.swing.JScrollPane ScrollPaneTable;
    private javax.swing.JButton btnDone;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
